# Cognitive Weaver Configuration

ai_model:
  provider: "deepseek"  # Options: openai, deepseek, ollama
  model_name: "deepseek-chat"  # Model name for the provider
  api_key: "sk-3bde3d12ab464212aec4be3113016b33"  # Your API key
  base_url: "https://api.deepseek.com"  # Base URL for API calls
  temperature: 0.1  # Controls randomness of AI responses

relations:
  predefined_relations:
    - "支撑观点"
    - "反驳观点"
    - "举例说明"
    - "定义概念"
    - "属于分类"
    - "包含部分"
    - "引出主题"
    - "简单提及"
  custom_relations: []  # Add custom relation types here

file_monitoring:
  watch_extensions:
    - ".md"
  context_window_size: 100  # Number of characters around links for context
  ignore_patterns:
    - "/.git/"
    - "/.obsidian/"

max_retries: 3  # Maximum retries for AI calls
backup_files: true  # Whether to create backups before modifying files
